#!/usr/bin/env node
// scripts/build-splash.mjs — deterministic ASCII pipeline (spec §5.2).
//
// Stages:
//   1. Source PNG  (docs/assets/sleepy-sloth-source.png, 1024x1024, CC0)
//   2. Tone curve  (ImageMagick `convert -colorspace Gray -level 10%,90%`)
//   3. Rasterise   (`chafa --symbols=braille --size=24x10 --fg-only`)
//   4. ANSI strip  (regex /\x1b\[[0-9;]*m/g — colour reapplied at runtime)
//   5. Validate    (string-width per row <= 24)
//   6. Emit        (tui/banner.generated.mjs)
//
// Runtime only depends on the committed banner.generated.mjs.
// chafa + ImageMagick are build-time only.
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import stringWidth from 'string-width';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const SRC = path.join(ROOT, 'docs/assets/sleepy-sloth-source.png');
const OUT = path.join(ROOT, 'tui/banner.generated.mjs');

function which(bin) {
  const r = spawnSync('which', [bin], { encoding: 'utf8' });
  return r.status === 0 ? r.stdout.trim() : null;
}

function main() {
  if (!which('chafa') || !which('convert')) {
    console.error('build-splash: chafa and ImageMagick `convert` are required.');
    console.error('  macOS:  brew install chafa imagemagick');
    console.error('  Debian: apt-get install chafa imagemagick');
    process.exit(2);
  }
  const work = mkdtempSync(path.join(tmpdir(), 'lazyclaw-splash-'));
  const toned = path.join(work, 'toned.png');

  // Stage 2: tone curve.
  execFileSync('convert', [SRC, '-colorspace', 'Gray', '-level', '10%,90%', toned]);

  // Stage 3: rasterise.
  const rasterRaw = execFileSync('chafa', [
    '--symbols=braille', '--size=24x10', '--fg-only',
    '--threshold=0.55', toned,
  ], { encoding: 'utf8' });

  // Stage 4: ANSI strip.
  const ansi = /\x1b\[[0-9;]*m/g;
  const rows = rasterRaw.split('\n').map((r) => r.replace(ansi, '')).filter((r) => r.length > 0);

  // Stage 5: validate.
  for (const [i, row] of rows.entries()) {
    const w = stringWidth(row);
    if (w > 24) {
      console.error(`row ${i} width=${w} exceeds 24: ${JSON.stringify(row)}`);
      process.exit(3);
    }
  }

  // Stage 6: emit.
  const body = `// AUTO-GENERATED by scripts/build-splash.mjs — do not edit by hand.\n`
    + `export const banner = ${JSON.stringify({
      rows,
      width: 24,
      height: rows.length,
      fg: '#FFB347',
    }, null, 2)};\n`;
  writeFileSync(OUT, body);
  console.log(`build-splash: wrote ${OUT} (${rows.length} rows)`);
}

main();
