#!/usr/bin/env node
// scripts/sync-models.mjs — refresh providers/models.generated.mjs from a
// real live fetch, one provider at a time, and print exactly what happened.
//
// This is the maintainer-run counterpart to the daemon's background model
// cache (daemon/lib/model_cache.mjs): the daemon refreshes an in-memory
// cache for as long as it runs; this script refreshes the file that layer
// falls back to when the in-memory cache is empty or stale, so the
// improvement lands even for a fresh checkout / a user with no credentials
// configured on their own machine.
//
// Hard rules (see providers/model_sync.mjs::mergeGeneratedModels):
//   - a provider with no credential configured here is SKIPPED — its
//     previous entry in the generated file is kept untouched, never cleared;
//   - a live fetch that succeeds but comes back empty does not overwrite a
//     previously non-empty entry either;
//   - every written entry carries its own provenance + fetchedAt timestamp;
//   - this script never invents a model id — every id printed/written came
//     from this run's network fetch or from the file's own prior content.
//
// Usage: npm run models:sync

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { readConfig } from '../lib/config.mjs';
import { ensureRegistry, getRegistry } from '../lib/registry_boot.mjs';
import { fetchAllLiveModels, mergeGeneratedModels } from '../providers/model_sync.mjs';

const REPO_ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const OUT_PATH = path.join(REPO_ROOT, 'providers', 'models.generated.mjs');

const HEADER = `// providers/models.generated.mjs — AUTO-GENERATED by \`npm run models:sync\`
// (scripts/sync-models.mjs). Do not hand-edit: the next sync overwrites this
// file wholesale, and no model id here was ever typed by hand — each one
// came from a live fetch (providers/model_sync.mjs), never from memory.
//
// This is the middle layer in the daemon's model-list resolution order —
// live in-memory cache -> this generated file -> the static suggestedModels
// in providers/registry.mjs — see daemon/lib/model_cache.mjs. A provider the
// sync script couldn't reach (no credential configured on the syncing
// machine) keeps whatever entry was here before; it is never cleared to an
// empty list.
`;

async function loadPrevious() {
  try {
    // Cache-bust so re-running this script within one process (tests) never
    // serves a stale module-cache copy of the file it's about to rewrite.
    const mod = await import(`${url.pathToFileURL(OUT_PATH).href}?t=${Date.now()}`);
    return mod.GENERATED_MODELS && typeof mod.GENERATED_MODELS === 'object' ? mod.GENERATED_MODELS : {};
  } catch {
    return {};
  }
}

// Every committed .mjs file is capped at 500 lines (scripts/lint-file-size.mjs)
// and this file must never be added to that gate's ALLOW ratchet. An
// aggregator provider (openrouter, nim, …) can return hundreds of model ids,
// so a one-id-per-line pretty-print would blow the cap the moment a real
// aggregator gets synced. Each provider's `models` array is therefore
// serialized on a single line — the file scales with the number of
// PROVIDERS (a handful), not with how many models each one has.
function serialize(next) {
  // Deterministic key order (alphabetical) so re-running with no real
  // changes produces a stable, diff-friendly file.
  const ids = Object.keys(next).sort();
  const body = ids.map((id, i) => {
    const entry = next[id];
    const comma = i < ids.length - 1 ? ',' : '';
    return `  ${JSON.stringify(id)}: {\n`
      + `    "models": ${JSON.stringify(entry.models)},\n`
      + `    "fetchedAt": ${JSON.stringify(entry.fetchedAt)},\n`
      + `    "provenance": ${JSON.stringify(entry.provenance)}\n`
      + `  }${comma}`;
  }).join('\n');
  return `${HEADER}export const GENERATED_MODELS = {\n${body}\n};\n`;
}

async function main() {
  await ensureRegistry();
  const cfg = readConfig();
  const reg = getRegistry();
  const previous = await loadPrevious();

  const results = await fetchAllLiveModels({
    cfg,
    providers: reg.PROVIDERS,
    providerInfo: reg.PROVIDER_INFO,
  });
  const { next, report } = mergeGeneratedModels({ previous, results });

  fs.writeFileSync(OUT_PATH, serialize(next));

  const synced = report.filter((r) => r.action === 'synced');
  const skipped = report.filter((r) => r.action === 'skipped');
  process.stdout.write(`models:sync — ${synced.length} synced, ${skipped.length} skipped\n\n`);
  for (const r of synced) {
    process.stdout.write(`  ✓ synced   ${r.providerId} (${r.count} model${r.count === 1 ? '' : 's'})\n`);
  }
  for (const r of skipped) {
    process.stdout.write(`  ⊘ skipped  ${r.providerId} — ${r.reason}\n`);
  }
  process.stdout.write(`\nwrote ${path.relative(REPO_ROOT, OUT_PATH)}\n`);
}

main().catch((err) => {
  process.stderr.write(`models:sync failed: ${err?.message || err}\n`);
  process.exit(1);
});
